# 1-> Go To create Account: https://allsportsapi.com/register
# 2-> Then Get Your Free Api Key from Here: https://allsportsapi.com/soccer-football-api
# 3-> Set Your API KEY HERE ?
API_KEY = a68f2077a2511cf6fa3ed1fc0ffc97217e9890cf96797f9339e2a1691f1a83e4
#NOW it's OK ?




# DON'T CHANGE ANYTHING DOWN HERE!!
BASE_URL = https://apiv2.allsportsapi.com/football/?APIkey=
SUB_URL = &timezone=Africa/Cairo&met=
